#!/usr/bin/env python

import sys
import os
import logging
import numpy as np
import h5py as h5

import warnings
warnings.filterwarnings("ignore")

import sip
sip.setapi("QString", 2)

import matplotlib as mpl
mpl.use('Qt4Agg')

import seaborn as sns

from matplotlib import style
style.use( u'seaborn-ticks')

from survos.qt_compat import QtGui, QtCore
from survos.widgets import MainWindow

root = logging.getLogger()
root.setLevel(logging.DEBUG)

ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.DEBUG)
root.addHandler(ch)

app = QtGui.QApplication(sys.argv)

with open(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'survos.qcs')) as f:
	css = f.read()

window = MainWindow("SuRVoS: Super-Region Volume Segmentation workbench")
window.setMinimumSize(1024, 768)
window.setStyleSheet(css)
window.showMaximized()

# Debug
if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]):
	window.load_workspace(sys.argv[1])

sys.exit(app.exec_())
