package:
  name: survos
  version: 1.1.1


build:
  preserve_egg_dir: False

    
requirements:
  build:
    - python x.x
    - numpy
    - scipy
    - cudatoolkit ==9.0
    - cython
    - cmake >=3.9
    - matplotlib
  run:
    - python x.x
    - numpy
    - scipy
    - cudatoolkit ==9.0
    - matplotlib
    - tifffile
    - scikit-image
    - scikit-learn
    - networkx
    - h5py
    - decorator
    - sip
    - seaborn
    - pyqt >=5.6
	
about:
  home: https://github.com/DiamondLightSource/SuRVoS
  license:  GPLv3 license
  summary: (Su)per (R)egion (Vo)lume (S)egmentaton workbench
